### ISSUE TITLE
Appendix:  import of sha3 failed, sha3 does not exist, description of the block and header structure ???

### ISSUE THREAD

**Issue by Danielhodali** [ethereum/wiki#489]
I tried to run the example described on https://github.com/ethereum/wiki/wiki/Ethash , but it failed. My questions:

- sha3 is missing. Where can I find sha3?
- What is the type (structure) of the used variables "block" and "header" ? Where are the block structure and header structure  described? 
- Which function is the entry point?

I am looking forward to  your answer

**Comment by Danielhodali** [comment]
Is anybody there ?

**Comment by bdwjn** [comment]
I've been trying to get that code to run too. A working example would be nice to have.

sha3 can be found here: https://github.com/bjornedstrom/python-sha3.

However I got stuck somewhere else: the mine function does ``nonce=randint(0,2**64)`` which means nonce is a regular Python integer. No byte string, no list, just an int. It then passes that value unchanged to hashimoto which fails on ``s = sha3_512(header + nonce[::-1])`` because you can't do `[::-1]` on an int...

**Comment by jamesray1** [comment]
You could also look in [client implementations](https://github.com/ethereum/wiki/wiki/Clients). Please see https://github.com/ethereum/wiki/wiki#issues-and-pull-requests for why this was closed.
