### ISSUE TITLE
Add NatSpec for events

### ISSUE THREAD

**Issue by fulldecent** [ethereum/wiki#605]
Presently events have application-specific meaning and they have no documentation. 

Add NatSpec for events so that mean can be specified.

**Comment by fulldecent** [comment]
Got it, thanks for the pointer. Could you please advise where is the correct place to propose changing the NatSpec format?

**Comment by jamesray1** [comment]
I didn't know who the NatSpec implementers are, but to oblige you:

Looking at https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format/_history it was created by @gavofyork and has had significant edits by @LefterisJP. Perhaps one of them could discuss the matter with you. Otherwise maybe you can submit an EIP.
